<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MissionControl.Agent-d9217845-4b51-4123-8bc7-894feb755468</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="JoyfulReaperLib.MissionControl" Version="0.0.1" />
    <PackageReference Include="JoyfulReaperLib.Sqlite" Version="0.0.9" />
  </ItemGroup>
</Project>
