<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MissionControl.Agent-d9217845-4b51-4123-8bc7-894feb755468</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JoyfulReaperLib.MissionControl" Version="0.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MissionControl.Contracts\MissionControl.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Publishing\" />
  </ItemGroup>
</Project>
