FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src
COPY . .

RUN dotnet restore \
    MissionControl.Archive/MissionControl.Archive.csproj

RUN dotnet publish \
    MissionControl.Archive/MissionControl.Archive.csproj \
    --configuration Release \
    --output /app/publish \
    --no-restore \
    /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080 \
    EventArchive__DatabaseFileName=mission-control.db \
    EventArchive__BasePath=/app/data

VOLUME ["/app/data"]

EXPOSE 8080

ENTRYPOINT ["dotnet", "MissionControl.Archive.dll"]
