<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MissionControl.Processor-bc703520-7552-4126-8ca5-16acff7a49a8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JoyfulReaperLib.Sqlite" Version="0.0.9" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MissionControl.Contracts\MissionControl.Contracts.csproj" />
  </ItemGroup>
</Project>
