<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

<ItemGroup>
	<PackageReference Include="JoyfulReaperLib.Sqlite" Version="0.0.9" />
	<PackageReference Include="Dapper" Version="2.1.79" />
	<PackageReference Include="JoyfulReaperLib.MissionControl" Version="0.0.1" />
</ItemGroup>

<ItemGroup>
	<InternalsVisibleTo Include="MissionControl.Tests" />
</ItemGroup>

<ItemGroup>
  <ProjectReference Include="..\MissionControl.Contracts\MissionControl.Contracts.csproj" />
</ItemGroup>

</Project>
