<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MissionControl.Processor-bc703520-7552-4126-8ca5-16acff7a49a8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JoyfulReaperLib.Sqlite" Version="0.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MissionControl.Contracts\MissionControl.Contracts.csproj" />
    <ProjectReference Include="..\MissionControl.Messaging.RabbitMq\MissionControl.Messaging.RabbitMq.csproj" />
    <ProjectReference Include="..\MissionControl.Messaging\MissionControl.Messaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Processing\RabbitMq\" />
  </ItemGroup>
</Project>
